# Write a python program to perform the following operations

## a) Print two square matrix of order 3 * 3 by taking input from the user

In [1]:
import numpy as np

a = np.zeros((3,3) , dtype = int)
b = np.zeros((3,3) , dtype = int)


In [18]:
for i in range(len(a)):
    for j in range(len(a[0])):
        a[i][j] = int(input(f'Enter A[{i}][{j}] element of matrix: '))

for i in range(len(b)):
    for j in range(len(b[0])):
        b[i][j] = int(input(f'Enter B[{i}][{j}] element of matrix: '))

print("\n Array A: \n",a)
print("\n Array B: \n",b)
               

Enter A[0][0] element of matrix: 4
Enter A[0][1] element of matrix: 8
Enter A[0][2] element of matrix: 6
Enter A[1][0] element of matrix: 2
Enter A[1][1] element of matrix: 0
Enter A[1][2] element of matrix: 8
Enter A[2][0] element of matrix: 2
Enter A[2][1] element of matrix: 4
Enter A[2][2] element of matrix: 10
Enter B[0][0] element of matrix: 2
Enter B[0][1] element of matrix: 4
Enter B[0][2] element of matrix: 3
Enter B[1][0] element of matrix: 1
Enter B[1][1] element of matrix: 1
Enter B[1][2] element of matrix: 2
Enter B[2][0] element of matrix: 2
Enter B[2][1] element of matrix: 4
Enter B[2][2] element of matrix: 5

 Array A: 
 [[ 4  8  6]
 [ 2  0  8]
 [ 2  4 10]]

 Array B: 
 [[2 4 3]
 [1 1 2]
 [2 4 5]]


## Preform the following operations using numpy functions:

### a) Addition

In [19]:
#addition of Matrix A and B
addMat = np.add(a,b)
#addMat = a + b
print('Resultant Matrix:\n', addMat)

Resultant Matrix:
 [[ 6 12  9]
 [ 3  1 10]
 [ 4  8 15]]


### b) Subtraction

In [20]:
#Subtraction of Matrix A and B
subMat = np.subtract(a,b)
#subMat = a-b
print('Resultant Matrix:\n',subMat)

Resultant Matrix:
 [[ 2  4  3]
 [ 1 -1  6]
 [ 0  0  5]]


### c) Division 

In [21]:
#division of Matrix A and B
divMat = np.divide(a,b)
#divMat = a/b
print('Matrix Division:\n',divMat)

Matrix Division:
 [[2. 2. 2.]
 [2. 0. 4.]
 [1. 1. 2.]]


## Perform matrix multiplication using loops

In [22]:
multiplyMat = np.zeros((3,3), dtype=int)
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):
            multiplyMat[i][j] = multiplyMat[i][j] + (a[i][k] * b[k][j])

print ('Multiplied Matrix:\n', multiplyMat)

Multiplied Matrix:
 [[28 48 58]
 [20 40 46]
 [28 52 64]]


In [23]:
mulMat = np.matmul(a,b)
#mulMat2 = np.dot(a,b)
#mulMat3 = a@b
print('Multiplied Matrix:\n',mulMat)

Multiplied Matrix:
 [[28 48 58]
 [20 40 46]
 [28 52 64]]


## Print transpose of both Matrix

In [24]:
tA = np.transpose(a)
print('A Transpose:\n', tA)


tB = np.transpose(b)
print('B Transpose:\n', tB)

A Transpose:
 [[ 4  2  2]
 [ 8  0  4]
 [ 6  8 10]]
B Transpose:
 [[2 1 2]
 [4 1 4]
 [3 2 5]]
